version: 0.2
env:
#  shell: shell-tag
  variables:
    S3_BUCKET: "standard-update-checker-builds"
#    key: "value"
#  parameter-store:
#    key: "value"
#    key: "value"
#  exported-variables:
#    - variable
#    - variable
#  secrets-manager:
#    key: secret-id:json-key:version-stage:version-id
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Installing all requirements
#      - python3 --version
#      - pip --version
#      - ls -a
      - pip install -r ./requirements.txt
      - pip install -r ./requirements-vendor.txt
  post_build:
    commands:
#      - echo Installing test requirements
#      - pip install -r ./requirements-tests.txt
#      - echo Running unit testes
#      - ./bin/tests/unit-coverage-no-report-html.sh
    finally:
       - echo Generating package file
       - ./bin/chalice/package.sh
       - aws cloudformation package --template-file sam.json --s3-bucket $S3_BUCKET --output-template-file packaged.yml
#reports:
#  UnitTestsReports:
#    files:
#      - 'target/unit/clover.xml'
#    file-format: 'CLOVERXML'
artifacts:
  files:
    - sam.json
    - packaged.yml
    - appspec.yaml
#    - ./dist/deployment.zip
#    - ./dist/sam.json
